server:
  port: 8080
  shutdown: graceful
  undertow:
    threads:
      worker: 24
      io: 3
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
    application-display-name: refugee
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: refugee
    main:
      banner-mode: off
    jackson:
      time-zone: UTC
      locale: en_US
    mvc:
      format:
        date: iso
        date-time: iso
    lifecycle:
      timeout-per-shutdown-phase: 30s
  error:
    whitelabel:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/refugee
    driver-class-name: org.postgresql.Driver
    username: refugee
    password: refugee
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  jdbc:
    template:
      fetch-size: 10
      max-rows: 10

swagger:
  host: localhost
  scheme: http
  title: RefugeeApi
  description: RefugeeApi

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-components: never
      show-details: never
      group:
        readiness:
          include: readinessState, db
  endpoints.web.exposure.include: "*"

springdoc:
  packagesToScan: ua.pomoc.refugee.api
  pathsToMatch: /**
  swagger-ui:
    enabled: true

logging.level:
  ROOT: info
  ua.pomoc.refugee: info
  org.springframework: info