spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/refugee
    driver-class-name: org.postgresql.Driver
    username: refugee
    password: refugee
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  jdbc:
    template:
      fetch-size: 10
      max-rows: 10

swagger:
  host: localhost
  scheme: http
  title: RefugeeApi
  description: RefugeeApi

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  packagesToScan: ua.pomoc.refugee.api
  pathsToMatch: /**
  swagger-ui:
    enabled: true