name: ci/cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          architecture: x64
      - name: Build
        if: github.ref == 'refs/heads/main'
        run: chmod +x gradlew &&\
          ./gradlew clean jib -x test
